### ISSUE TITLE
Define environment variables based on the output of commands

### ISSUE THREAD

**Issue by breml** [FooSoft/homemaker#17]
I would like to be able to define additional environment variables based on the output of a command. As a practical example, I would like to set an environment variable `HOSTNAME`, with the result of the command `hostname -s` as the value.
I could implement this on my own, but I would like to get your opinion about the right way to configure this.

Possibilities which come to my mind:

1. New configuration element

```
[tasks.envs]
    cmdenvs = [ [ "HOSTNAME", "hostname", "-s" ] ]
```

2. Extension of the existing `envs`, e.g. with a macro/placeholder, which evaluates the additional arguments:

```
[tasks.envs]
    envs = [ [ "HOSTNAME", "@exec", "hostname", "-s" ] ]
```

**Comment by FooSoft** [comment]
I really like the second option because it provides advanced functionality without expanding the overall number of the "block" properties. I would suggest using `!` instead of `@` character as the escape just so that there is no confusion with macros. In many tools (such as vim), `!` also implies executing a shell command, so folks familiar with that will have an easier time. In the future, it also gives us the option of potentially catching `stderr` if that is something that anybody needs (presumably, just by using a different character).
